In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

In [2]:
%pip install jupyterlab_play_cell_button

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: jupyterlab_play_cell_button in c:\users\fernando araiza\appdata\roaming\python\python39\site-packages (1.0.0)
Requirement already satisfied: jupyter-server<2,>=1.6 in c:\programdata\anaconda3\lib\site-packages (from jupyterlab_play_cell_button) (1.18.1)
Requirement already satisfied: pyzmq>=17 in c:\programdata\anaconda3\lib\site-packages (from jupyter-server<2,>=1.6->jupyterlab_play_cell_button) (23.2.0)
Requirement already satisfied: tornado>=6.1.0 in c:\programdata\anaconda3\lib\site-packages (from jupyter-server<2,>=1.6->jupyterlab_play_cell_button) (6.1)
Requirement already satisfied: nbconvert>=6.4.4 in c:\programdata\anaconda3\lib\site-packages (from jupyter-server<2,>=1.6->jupyterlab_play_cell_button) (6.4.4)
Requirement already satisfied: pywinpty in c:\programdata\anaconda3\lib\site-packages (from jupyter-server<2,>=1.6->jupyterlab_play_cell_button) (2.0.2)
Requirement already satisfied: jupyter-client>=6.1.12 in c:\programdata\anaconda3\lib\site-packages (from jupyter-server<2,>=1.6->jupyterlab_play_cell_button) (7.3.4)
Requirement already satisfied: prometheus-client in c:\programdata\anaconda3\lib\site-packages (from jupyter-server<2,>=1.6->jupyterlab_play_cell_button) (0.14.1)
Requirement already satisfied: jupyter-core>=4.7.0 in c:\programdata\anaconda3\lib\site-packages (from jupyter-server<2,>=1.6->jupyterlab_play_cell_button) (4.11.1)
Requirement already satisfied: argon2-cffi in c:\programdata\anaconda3\lib\site-packages (from jupyter-server<2,>=1.6->jupyterlab_play_cell_button) (21.3.0)
Requirement already satisfied: terminado>=0.8.3 in c:\programdata\anaconda3\lib\site-packages (from jupyter-server<2,>=1.6->jupyterlab_play_cell_button) (0.13.1)
Requirement already satisfied: jinja2 in c:\programdata\anaconda3\lib\site-packages (from jupyter-server<2,>=1.6->jupyterlab_play_cell_button) (2.11.3)
Requirement already satisfied: nbformat>=5.2.0 in c:\programdata\anaconda3\lib\site-packages (from jupyter-server<2,>=1.6->jupyterlab_play_cell_button) (5.5.0)
Requirement already satisfied: Send2Trash in c:\programdata\anaconda3\lib\site-packages (from jupyter-server<2,>=1.6->jupyterlab_play_cell_button) (1.8.0)
Requirement already satisfied: packaging in c:\programdata\anaconda3\lib\site-packages (from jupyter-server<2,>=1.6->jupyterlab_play_cell_button) (21.3)
Requirement already satisfied: traitlets>=5.1 in c:\programdata\anaconda3\lib\site-packages (from jupyter-server<2,>=1.6->jupyterlab_play_cell_button) (5.1.1)
Requirement already satisfied: websocket-client in c:\programdata\anaconda3\lib\site-packages (from jupyter-server<2,>=1.6->jupyterlab_play_cell_button) (0.58.0)
Requirement already satisfied: anyio<4,>=3.1.0 in c:\programdata\anaconda3\lib\site-packages (from jupyter-server<2,>=1.6->jupyterlab_play_cell_button) (3.5.0)
Requirement already satisfied: idna>=2.8 in c:\programdata\anaconda3\lib\site-packages (from anyio<4,>=3.1.0->jupyter-server<2,>=1.6->jupyterlab_play_cell_button) (3.3)
Requirement already satisfied: sniffio>=1.1 in c:\programdata\anaconda3\lib\site-packages (from anyio<4,>=3.1.0->jupyter-server<2,>=1.6->jupyterlab_play_cell_button) (1.2.0)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\programdata\anaconda3\lib\site-packages (from jupyter-client>=6.1.12->jupyter-server<2,>=1.6->jupyterlab_play_cell_button) (2.8.2)
Requirement already satisfied: nest-asyncio>=1.5.4 in c:\programdata\anaconda3\lib\site-packages (from jupyter-client>=6.1.12->jupyter-server<2,>=1.6->jupyterlab_play_cell_button) (1.5.5)
Requirement already satisfied: entrypoints in c:\programdata\anaconda3\lib\site-packages (from jupyter-client>=6.1.12->jupyter-server<2,>=1.6->jupyterlab_play_cell_button) (0.4)
Requirement already satisfied: pywin32>=1.0 in c:\programdata\anaconda3\lib\site-packages (from jupyter-core>=4.7.0->jupyter-server<2,>=1.6->jupyterlab_play_cell_button) (302)
Requirement already satisfied: pandocfilters>=1.4.1 in c:\programdata\anaconda3\lib\site-packages (from nbconvert>=6.4.4->jupyter-server<2,>=1.6->jupyterlab_play_cell_button) (1.5.0)
Requirement already satisfied: mistune<2,>=0.8.1 in c:\programdata\anaconda3\lib\site-packages (from nbconvert>=6.4.4->jupyter-server<2,>=1.6->jupyterlab_play_cell_button) (0.8.4)
Requirement already satisfied: nbclient<0.6.0,>=0.5.0 in c:\programdata\anaconda3\lib\site-packages (from nbconvert>=6.4.4->jupyter-server<2,>=1.6->jupyterlab_play_cell_button) (0.5.13)
Requirement already satisfied: defusedxml in c:\programdata\anaconda3\lib\site-packages (from nbconvert>=6.4.4->jupyter-server<2,>=1.6->jupyterlab_play_cell_button) (0.7.1)
Requirement already satisfied: jupyterlab-pygments in c:\programdata\anaconda3\lib\site-packages (from nbconvert>=6.4.4->jupyter-server<2,>=1.6->jupyterlab_play_cell_button) (0.1.2)
Requirement already satisfied: testpath in c:\programdata\anaconda3\lib\site-packages (from nbconvert>=6.4.4->jupyter-server<2,>=1.6->jupyterlab_play_cell_button) (0.6.0)
Requirement already satisfied: bleach in c:\programdata\anaconda3\lib\site-packages (from nbconvert>=6.4.4->jupyter-server<2,>=1.6->jupyterlab_play_cell_button) (4.1.0)
Requirement already satisfied: beautifulsoup4 in c:\programdata\anaconda3\lib\site-packages (from nbconvert>=6.4.4->jupyter-server<2,>=1.6->jupyterlab_play_cell_button) (4.11.1)
Requirement already satisfied: pygments>=2.4.1 in c:\programdata\anaconda3\lib\site-packages (from nbconvert>=6.4.4->jupyter-server<2,>=1.6->jupyterlab_play_cell_button) (2.11.2)
Requirement already satisfied: MarkupSafe>=0.23 in c:\programdata\anaconda3\lib\site-packages (from jinja2->jupyter-server<2,>=1.6->jupyterlab_play_cell_button) (2.0.1)
Requirement already satisfied: fastjsonschema in c:\programdata\anaconda3\lib\site-packages (from nbformat>=5.2.0->jupyter-server<2,>=1.6->jupyterlab_play_cell_button) (2.16.2)
Requirement already satisfied: jsonschema>=2.6 in c:\programdata\anaconda3\lib\site-packages (from nbformat>=5.2.0->jupyter-server<2,>=1.6->jupyterlab_play_cell_button) (4.16.0)
Requirement already satisfied: argon2-cffi-bindings in c:\programdata\anaconda3\lib\site-packages (from argon2-cffi->jupyter-server<2,>=1.6->jupyterlab_play_cell_button) (21.2.0)
Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in c:\programdata\anaconda3\lib\site-packages (from packaging->jupyter-server<2,>=1.6->jupyterlab_play_cell_button) (3.0.9)
Requirement already satisfied: six in c:\programdata\anaconda3\lib\site-packages (from websocket-client->jupyter-server<2,>=1.6->jupyterlab_play_cell_button) (1.16.0)
Requirement already satisfied: attrs>=17.4.0 in c:\programdata\anaconda3\lib\site-packages (from jsonschema>=2.6->nbformat>=5.2.0->jupyter-server<2,>=1.6->jupyterlab_play_cell_button) (21.4.0)
Requirement already satisfied: pyrsistent!=0.17.0,!=0.17.1,!=0.17.2,>=0.14.0 in c:\programdata\anaconda3\lib\site-packages (from jsonschema>=2.6->nbformat>=5.2.0->jupyter-server<2,>=1.6->jupyterlab_play_cell_button) (0.18.0)
Requirement already satisfied: cffi>=1.0.1 in c:\programdata\anaconda3\lib\site-packages (from argon2-cffi-bindings->argon2-cffi->jupyter-server<2,>=1.6->jupyterlab_play_cell_button) (1.15.1)
Requirement already satisfied: soupsieve>1.2 in c:\programdata\anaconda3\lib\site-packages (from beautifulsoup4->nbconvert>=6.4.4->jupyter-server<2,>=1.6->jupyterlab_play_cell_button) (2.3.1)
Requirement already satisfied: webencodings in c:\programdata\anaconda3\lib\site-packages (from bleach->nbconvert>=6.4.4->jupyter-server<2,>=1.6->jupyterlab_play_cell_button) (0.5.1)
Requirement already satisfied: pycparser in c:\programdata\anaconda3\lib\site-packages (from cffi>=1.0.1->argon2-cffi-bindings->argon2-cffi->jupyter-server<2,>=1.6->jupyterlab_play_cell_button) (2.21)
Note: you may need to restart the kernel to use updated packages.

In [3]:
df = pd.read_csv(r'C:\data\mia_data2.csv')

In [4]:
df.keys()

Index(['Unnamed: 0.1', 'Unnamed: 0', 'YEAR', 'MONTH', 'DAY_OF_WEEK',
       'OP_CARRIER_FL_NUM', 'ORIGIN', 'DEST', 'CRS_DEP_TIME', 'DEP_TIME',
       'DEP_DELAY', 'DEP_DELAY_NEW', 'CRS_ARR_TIME', 'ARR_TIME', 'ARR_DELAY',
       'ARR_DELAY_NEW', 'CANCELLED', 'CANCELLATION_CODE', 'DIVERTED',
       'CRS_ELAPSED_TIME', 'ACTUAL_ELAPSED_TIME', 'CARRIER_DELAY',
       'WEATHER_DELAY', 'NAS_DELAY', 'SECURITY_DELAY', 'LATE_AIRCRAFT_DELAY',
       'WHY_DELAY', 'DAY', 'DATE'],
      dtype='object')

In [5]:
# I want to create dummy values based on the why delay column
dummy = pd.get_dummies(df['WHY_DELAY'])

In [6]:
dummy

        0  carrier  late aircraft  nas  security  weather
0       1        0              0    0         0        0
1       1        0              0    0         0        0
2       1        0              0    0         0        0
3       1        0              0    0         0        0
4       1        0              0    0         0        0
...    ..      ...            ...  ...       ...      ...
736647  1        0              0    0         0        0
736648  1        0              0    0         0        0
736649  1        0              0    0         0        0
736650  0        0              0    1         0        0
736651  0        1              0    0         0        0

[736652 rows x 6 columns]

In [7]:
df = pd.concat([df, dummy], axis = 1)
df.keys()

Index(['Unnamed: 0.1', 'Unnamed: 0', 'YEAR', 'MONTH', 'DAY_OF_WEEK',
       'OP_CARRIER_FL_NUM', 'ORIGIN', 'DEST', 'CRS_DEP_TIME', 'DEP_TIME',
       'DEP_DELAY', 'DEP_DELAY_NEW', 'CRS_ARR_TIME', 'ARR_TIME', 'ARR_DELAY',
       'ARR_DELAY_NEW', 'CANCELLED', 'CANCELLATION_CODE', 'DIVERTED',
       'CRS_ELAPSED_TIME', 'ACTUAL_ELAPSED_TIME', 'CARRIER_DELAY',
       'WEATHER_DELAY', 'NAS_DELAY', 'SECURITY_DELAY', 'LATE_AIRCRAFT_DELAY',
       'WHY_DELAY', 'DAY', 'DATE', '0', 'carrier', 'late aircraft', 'nas',
       'security', 'weather'],
      dtype='object')

In [8]:
df.drop(columns = ['Unnamed: 0.1', 'Unnamed: 0', 'OP_CARRIER_FL_NUM', 'CANCELLATION_CODE', 'DIVERTED',  'CARRIER_DELAY','WEATHER_DELAY', 'NAS_DELAY', 'SECURITY_DELAY', 'LATE_AIRCRAFT_DELAY', 'DATE', 'WHY_DELAY', 'carrier', 'late aircraft', 'nas','security', 'OP_CARRIER_FL_NUM']  , inplace = True)

In [9]:
# I need to create two data frames to work on one that is about departures from MIA and the 
#other one that deals with arrivals.

df_arr = df[df.DEST == 'MIA']
df_dep = df[df.ORIGIN == 'MIA']

In [10]:
# In df_ arr, the DEST value is the same for all flights, I will be eliminating that column as well as everything that has to 
# deal with departures.

df_arr.drop(columns = ['DEST', 'CRS_DEP_TIME', 'DEP_TIME', 'DEP_DELAY_NEW', 'CANCELLED'], inplace = True)

C:\Users\Fernando Araiza\AppData\Local\Temp\ipykernel_8888\4193388566.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_arr.drop(columns = ['DEST', 'CRS_DEP_TIME', 'DEP_TIME', 'DEP_DELAY_NEW', 'CANCELLED'], inplace = True)

In [11]:
# Converting Origin to numerical data by using get_dummies.
temp = pd.get_dummies(df_arr.ORIGIN, prefix = 'ORIGIN')

In [12]:
temp

,ORIGIN_ATL,ORIGIN_AUS,ORIGIN_BDL,ORIGIN_BGR,ORIGIN_BHM,ORIGIN_BNA,ORIGIN_BOS,ORIGIN_BWI,ORIGIN_CAE,ORIGIN_CHS,...,ORIGIN_SLC,ORIGIN_STL,ORIGIN_STT,ORIGIN_STX,ORIGIN_TLH,ORIGIN_TPA,ORIGIN_TTN,ORIGIN_TUL,ORIGIN_TYS,ORIGIN_XNA
0,0,0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
736642,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
736644,0,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
736645,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
736647,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
736648,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [13]:
#Join the two dataframes
df_arr = pd.concat([df_arr, temp], axis = 1)

In [14]:
y_arr = df_arr['weather']

In [15]:
df_arr.drop(columns = ['weather', 'ORIGIN'], inplace = True)

In [16]:
df_arr

,YEAR,MONTH,DAY_OF_WEEK,DEP_DELAY,CRS_ARR_TIME,ARR_TIME,ARR_DELAY,ARR_DELAY_NEW,CRS_ELAPSED_TIME,ACTUAL_ELAPSED_TIME,...,ORIGIN_SLC,ORIGIN_STL,ORIGIN_STT,ORIGIN_STX,ORIGIN_TLH,ORIGIN_TPA,ORIGIN_TTN,ORIGIN_TUL,ORIGIN_TYS,ORIGIN_XNA
0,2010,5,6.0,-16.0,1840,1835.0,-5.0,0.0,185.0,196.0,...,0,0,1,0,0,0,0,0,0,0
1,2010,5,7.0,15.0,1840,1840.0,0.0,0.0,185.0,170.0,...,0,0,1,0,0,0,0,0,0,0
2,2010,5,1.0,15.0,1840,1846.0,6.0,6.0,185.0,176.0,...,0,0,1,0,0,0,0,0,0,0
3,2010,5,2.0,-2.0,1840,1829.0,-11.0,0.0,185.0,176.0,...,0,0,1,0,0,0,0,0,0,0
4,2010,5,3.0,22.0,1840,1848.0,8.0,8.0,185.0,171.0,...,0,0,1,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
736642,2021,9,4.0,-8.0,1451,1444.0,-7.0,0.0,181.0,182.0,...,0,0,0,0,0,0,0,0,0,0
736644,2021,9,4.0,-3.0,1125,1110.0,-15.0,0.0,210.0,198.0,...,0,0,0,0,0,0,0,0,0,0
736645,2021,9,4.0,-3.0,1123,1120.0,-3.0,0.0,173.0,173.0,...,0,0,0,0,0,0,0,0,0,0
736647,2021,9,4.0,-4.0,1016,1009.0,-7.0,0.0,171.0,168.0,...,0,0,0,0,0,0,0,0,0,0
736648,2021,9,4.0,-3.0,12,5.0,-7.0,0.0,107.0,103.0,...,0,0,0,0,0,0,0,0,0,0

In [17]:
df_arr.keys()

Index(['YEAR', 'MONTH', 'DAY_OF_WEEK', 'DEP_DELAY', 'CRS_ARR_TIME', 'ARR_TIME',
       'ARR_DELAY', 'ARR_DELAY_NEW', 'CRS_ELAPSED_TIME', 'ACTUAL_ELAPSED_TIME',
       'DAY', '0', 'ORIGIN_ATL', 'ORIGIN_AUS', 'ORIGIN_BDL', 'ORIGIN_BGR',
       'ORIGIN_BHM', 'ORIGIN_BNA', 'ORIGIN_BOS', 'ORIGIN_BWI', 'ORIGIN_CAE',
       'ORIGIN_CHS', 'ORIGIN_CLE', 'ORIGIN_CLT', 'ORIGIN_CMH', 'ORIGIN_CVG',
       'ORIGIN_DAL', 'ORIGIN_DCA', 'ORIGIN_DEN', 'ORIGIN_DFW', 'ORIGIN_DSM',
       'ORIGIN_DTW', 'ORIGIN_EWR', 'ORIGIN_EYW', 'ORIGIN_GNV', 'ORIGIN_GSO',
       'ORIGIN_GSP', 'ORIGIN_HOU', 'ORIGIN_HSV', 'ORIGIN_IAD', 'ORIGIN_IAH',
       'ORIGIN_IND', 'ORIGIN_ISP', 'ORIGIN_JAN', 'ORIGIN_JAX', 'ORIGIN_JFK',
       'ORIGIN_LAS', 'ORIGIN_LAX', 'ORIGIN_LGA', 'ORIGIN_LIT', 'ORIGIN_MCI',
       'ORIGIN_MCO', 'ORIGIN_MDW', 'ORIGIN_MEM', 'ORIGIN_MKE', 'ORIGIN_MSP',
       'ORIGIN_MSY', 'ORIGIN_MYR', 'ORIGIN_OKC', 'ORIGIN_OMA', 'ORIGIN_ORD',
       'ORIGIN_ORF', 'ORIGIN_PHL', 'ORIGIN_PHX', 'ORIGIN_PIT', 'ORIGIN_PNS',
       'ORIGIN_PVD', 'ORIGIN_PWM', 'ORIGIN_RDU', 'ORIGIN_RIC', 'ORIGIN_ROC',
       'ORIGIN_RSW', 'ORIGIN_SAN', 'ORIGIN_SAT', 'ORIGIN_SAV', 'ORIGIN_SDF',
       'ORIGIN_SEA', 'ORIGIN_SFO', 'ORIGIN_SJU', 'ORIGIN_SLC', 'ORIGIN_STL',
       'ORIGIN_STT', 'ORIGIN_STX', 'ORIGIN_TLH', 'ORIGIN_TPA', 'ORIGIN_TTN',
       'ORIGIN_TUL', 'ORIGIN_TYS', 'ORIGIN_XNA'],
      dtype='object')

In [18]:
X_arr_train, X_arr_test, y_arr_train, y_arr_test = train_test_split(df_arr, y_arr, test_size = .33, random_state = 42)

In [19]:
df_dep.head()

,YEAR,MONTH,DAY_OF_WEEK,ORIGIN,DEST,CRS_DEP_TIME,DEP_TIME,DEP_DELAY,DEP_DELAY_NEW,CRS_ARR_TIME,ARR_TIME,ARR_DELAY,ARR_DELAY_NEW,CANCELLED,CRS_ELAPSED_TIME,ACTUAL_ELAPSED_TIME,DAY,0,weather
44,2010,5,6.0,MIA,IAH,1450,1446.0,-4.0,0.0,1640,1633.0,-7.0,0.0,0.0,170.0,167.0,1,1,0
45,2010,5,7.0,MIA,IAH,1450,1447.0,-3.0,0.0,1640,1633.0,-7.0,0.0,0.0,170.0,166.0,2,1,0
46,2010,5,1.0,MIA,IAH,1450,1447.0,-3.0,0.0,1640,1622.0,-18.0,0.0,0.0,170.0,155.0,3,1,0
47,2010,5,2.0,MIA,IAH,1450,1456.0,6.0,6.0,1640,1639.0,-1.0,0.0,0.0,170.0,163.0,4,1,0
48,2010,5,3.0,MIA,IAH,1450,1553.0,63.0,63.0,1640,1732.0,52.0,52.0,0.0,170.0,159.0,5,0,0

In [20]:
#Going to do the same things to df_dep that I just did with df_arr
df_dep.drop(columns = ['ORIGIN', 'CRS_ARR_TIME', 'ARR_TIME', 'ARR_DELAY', 'ARR_DELAY_NEW', 'CANCELLED'], inplace = True)

C:\Users\Fernando Araiza\AppData\Local\Temp\ipykernel_8888\889014205.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_dep.drop(columns = ['ORIGIN', 'CRS_ARR_TIME', 'ARR_TIME', 'ARR_DELAY', 'ARR_DELAY_NEW', 'CANCELLED'], inplace = True)

In [21]:
# Converting DEST to numerical data by using get_dummies.
temp = pd.get_dummies(df_dep.DEST, prefix = 'ORIGIN')

In [22]:
temp

,ORIGIN_ATL,ORIGIN_AUS,ORIGIN_BDL,ORIGIN_BGR,ORIGIN_BHM,ORIGIN_BNA,ORIGIN_BOS,ORIGIN_BWI,ORIGIN_CAE,ORIGIN_CHS,...,ORIGIN_SLC,ORIGIN_STL,ORIGIN_STT,ORIGIN_STX,ORIGIN_TLH,ORIGIN_TPA,ORIGIN_TTN,ORIGIN_TUL,ORIGIN_TYS,ORIGIN_XNA
44,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
45,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
46,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
47,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
48,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
736643,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
736646,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
736649,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
736650,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
736651,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [23]:
#Join the two dataframes
df_dep = pd.concat([df_dep, temp], axis = 1)

In [24]:
y_dep = df_dep['weather']

In [25]:
df_dep.drop(columns = ['weather', 'DEST'], inplace = True)

In [26]:
df_dep.keys()

Index(['YEAR', 'MONTH', 'DAY_OF_WEEK', 'CRS_DEP_TIME', 'DEP_TIME', 'DEP_DELAY',
       'DEP_DELAY_NEW', 'CRS_ELAPSED_TIME', 'ACTUAL_ELAPSED_TIME', 'DAY', '0',
       'ORIGIN_ATL', 'ORIGIN_AUS', 'ORIGIN_BDL', 'ORIGIN_BGR', 'ORIGIN_BHM',
       'ORIGIN_BNA', 'ORIGIN_BOS', 'ORIGIN_BWI', 'ORIGIN_CAE', 'ORIGIN_CHS',
       'ORIGIN_CLE', 'ORIGIN_CLT', 'ORIGIN_CMH', 'ORIGIN_CVG', 'ORIGIN_DAL',
       'ORIGIN_DCA', 'ORIGIN_DEN', 'ORIGIN_DFW', 'ORIGIN_DSM', 'ORIGIN_DTW',
       'ORIGIN_EGE', 'ORIGIN_EWR', 'ORIGIN_EYW', 'ORIGIN_GNV', 'ORIGIN_GSO',
       'ORIGIN_GSP', 'ORIGIN_HOU', 'ORIGIN_HSV', 'ORIGIN_IAD', 'ORIGIN_IAH',
       'ORIGIN_IND', 'ORIGIN_ISP', 'ORIGIN_JAN', 'ORIGIN_JAX', 'ORIGIN_JFK',
       'ORIGIN_LAS', 'ORIGIN_LAX', 'ORIGIN_LGA', 'ORIGIN_LIT', 'ORIGIN_MCI',
       'ORIGIN_MCO', 'ORIGIN_MDW', 'ORIGIN_MEM', 'ORIGIN_MKE', 'ORIGIN_MSP',
       'ORIGIN_MSY', 'ORIGIN_MYR', 'ORIGIN_OKC', 'ORIGIN_OMA', 'ORIGIN_ORD',
       'ORIGIN_ORF', 'ORIGIN_PBI', 'ORIGIN_PHL', 'ORIGIN_PHX', 'ORIGIN_PIT',
       'ORIGIN_PNS', 'ORIGIN_PVD', 'ORIGIN_PWM', 'ORIGIN_RDU', 'ORIGIN_RIC',
       'ORIGIN_ROC', 'ORIGIN_RSW', 'ORIGIN_SAN', 'ORIGIN_SAT', 'ORIGIN_SAV',
       'ORIGIN_SDF', 'ORIGIN_SEA', 'ORIGIN_SFO', 'ORIGIN_SJU', 'ORIGIN_SLC',
       'ORIGIN_STL', 'ORIGIN_STT', 'ORIGIN_STX', 'ORIGIN_TLH', 'ORIGIN_TPA',
       'ORIGIN_TTN', 'ORIGIN_TUL', 'ORIGIN_TYS', 'ORIGIN_XNA'],
      dtype='object')

In [38]:
df_dep.isnull().sum()

YEAR                0
MONTH               0
DAY_OF_WEEK     32329
CRS_DEP_TIME        0
DEP_TIME        36956
                ...
ORIGIN_TPA          0
ORIGIN_TTN          0
ORIGIN_TUL          0
ORIGIN_TYS          0
ORIGIN_XNA          0
Length: 90, dtype: int64

In [29]:
X_dep_train, X_dep_test, y_dep_train, y_dep_test = train_test_split(df_dep, y_dep, test_size = .33, random_state = 42)

In [30]:
# The data is not balanced
X_dep_train['0'].value_counts()

1    186970
0     59835
Name: 0, dtype: int64

In [31]:
y_dep_test.value_counts()

0    117333
1      4228
Name: weather, dtype: int64

In [32]:
!pip install imbalanced-learn

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: imbalanced-learn in c:\users\fernando araiza\appdata\roaming\python\python39\site-packages (0.10.1)
Requirement already satisfied: numpy>=1.17.3 in c:\programdata\anaconda3\lib\site-packages (from imbalanced-learn) (1.21.5)
Requirement already satisfied: scipy>=1.3.2 in c:\programdata\anaconda3\lib\site-packages (from imbalanced-learn) (1.9.1)
Requirement already satisfied: joblib>=1.1.1 in c:\users\fernando araiza\appdata\roaming\python\python39\site-packages (from imbalanced-learn) (1.2.0)
Requirement already satisfied: scikit-learn>=1.0.2 in c:\programdata\anaconda3\lib\site-packages (from imbalanced-learn) (1.0.2)
Requirement already satisfied: threadpoolctl>=2.0.0 in c:\programdata\anaconda3\lib\site-packages (from imbalanced-learn) (2.2.0)

In [33]:
from imblearn.over_sampling import SMOTE
sm = SMOTE(random_state = 42)
X_dep_train, y_dep_train = sm.fit_resample(X_dep_train, y_dep_train)

ValueError: Input contains NaN, infinity or a value too large for dtype('float64').